### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DerGoogler** [DerGoogler/dgm-cms#14]
This is the official roadmap of DGM-CMS!

- [ ] Allowing custom theme colors
- [ ] Without `config.js` configuration on the hosted page (it will an `*.json` file in the `/pages/config/` path. File name will be `page.config.json`
- [x] Open links always in new window
   
Submit issues with some function request
